apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: customer-api
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - prod
  selector:
    matchLabels:
      app: customer-api
  endpoints:
  - port: http
    path: /metrics